#EMPTY

---

#LEARNING RATE:

#variables
float64 learning_rate

#==================================================#
#LOSS FUNCTION:

#enums
uint8 CROSS_ENTROPY = 0
uint8 MEAN_SQUARED_ERROR = 1

#variables
uint8 loss_function

#==================================================#
#OPTIMISER:

#enums
uint8 STOCHASTIC_GRADIENT_DECENT = 0
uint8 MOMENTUM = 1
uint8 ADAGRAD = 2
uint8 RMSPROP = 3
uint8 ADAM = 4
uint8 ADAMAX = 5
uint8 GRADIENT_DECENT = 6

#variables
uint8 optimiser

#==================================================#
#CONVOLUTIONAL NETWORK:

#variables
bool convolutional_net_enabled #true or false?

#==================================================#
#LAYERS:

#enums
#activations
uint8 TANH = 0
uint8 ASINH = 1
uint8 SIGMOID = 2
uint8 RELU = 3
uint8 LEAKY_RELU = 4
uint8 SOFTMAX = 5
uint8 LINEAR = 6

#variables
uint8 number_of_layers
uint8[] layer_activations
uint64[] layer_neuron_count

#==================================================#
#MULTIPLIERS:

#variables
float64 input_multiplier
float64 output_multiplier
float64 closed_loop_error_multiplier
